/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ClientSession {
  /** Begin a transaction on this session. */
  startTransaction(): void
  /** Commit the current transaction. */
  commitTransaction(): void
  /** Abort / roll back the current transaction. */
  abortTransaction(): void
  /**
   * Insert a single document into a collection within this transaction.
   *
   * Returns `{ insertedId: string }`.
   */
  insertOne(collectionName: string, document: any): any
  /** Find a single document within this transaction. */
  findOne(collectionName: string, filter: any): any | null
  /** Find all documents matching the filter within this transaction. */
  find(collectionName: string, filter: any): any
  /**
   * Update a single document within this transaction.
   *
   * Returns `{ matchedCount, modifiedCount }`.
   */
  updateOne(collectionName: string, filter: any, update: any): any
  /**
   * Update all documents matching the filter within this transaction.
   *
   * Returns `{ matchedCount, modifiedCount }`.
   */
  updateMany(collectionName: string, filter: any, update: any): any
  /**
   * Delete a single document within this transaction.
   *
   * Returns `{ deletedCount }`.
   */
  deleteOne(collectionName: string, filter: any): any
  /**
   * Delete all documents matching the filter within this transaction.
   *
   * Returns `{ deletedCount }`.
   */
  deleteMany(collectionName: string, filter: any): any
  /** Count documents matching the filter within this transaction. */
  countDocuments(collectionName: string, filter?: any | undefined | null): number
}

export declare class Collection {
  /**
   * Release the underlying WiredTiger session and collection handle.
   *
   * Must be called before `db.dropCollection()` when a JS-side handle
   * was previously obtained for the same collection name, because
   * WiredTiger refuses to drop tables while any session holds cached
   * cursors on them.
   */
  close(): void
  insertOne(document: any): any
  insertMany(documents: any): any
  findOne(filter: any, options?: any | undefined | null): any | null
  find(filter: any, options?: any | undefined | null): any
  updateOne(filter: any, update: any, options?: any | undefined | null): any
  updateMany(filter: any, update: any, options?: any | undefined | null): any
  deleteOne(filter: any): any
  deleteMany(filter: any): any
  countDocuments(filter?: any | undefined | null): number
  aggregate(pipeline: any): any
  explainAggregate(pipeline: any): any
  createIndex(keys: any, options?: any | undefined | null): string
  reapExpired(): number
  dropIndex(name: string): void
  listIndexes(): any
}

export declare class Database {
  /** Open or create a database at the given path. */
  static open(path: string): Database
  /** Get the database name (derived from the path). */
  get name(): string
  /** Get the database path. */
  get path(): string
  /** Get or create a collection. */
  collection(name: string): Collection
  /** List all collection names in the database. */
  listCollectionNames(): Array<string>
  /** Drop a collection by name. */
  dropCollection(name: string): void
  /** Get database statistics. */
  stats(): any
  /**
   * Start a new client session for multi-collection transactions.
   *
   * Returns a `ClientSession` that supports `startTransaction()`,
   * `commitTransaction()`, and `abortTransaction()`, with collection
   * operations scoped to the transaction.
   */
  startSession(): ClientSession
  /**
   * Reap expired documents from all TTL-indexed collections.
   *
   * Returns the total number of documents removed.
   */
  reapTtl(): number
}

export declare class MongoClient {
  /**
   * Create a new MongoClient.
   *
   * Accepts a URI-like path: `local://./my_data` or just a filesystem path.
   */
  constructor(uri: string)
  /** Open a named database under the client's base path. */
  db(name: string): Database
}
