[package]
name = "smongo-py"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Python bindings for smongo embedded database"

[lib]
name = "_smongo_core"
crate-type = ["cdylib"]

[dependencies]
smongo-engine = { path = "../smongo-engine" }
wiredtiger-sys = { path = "../wiredtiger-sys" }
pyo3 = "0.28"
hex = "0.4"
getrandom = "0.2"
bson = "2"
sha2 = "0.10"
uuid = { version = "1", features = ["v4"] }
rand = "0.8"
crc32c = "0.6"
flate2 = "1"
snap = "1"
zstd = { version = "0.13", default-features = false }
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "sync", "signal", "macros", "time"] }
bytes = "1"
parking_lot = "0.12.5"
tokio-rustls = "0.26"
rustls-pemfile = "2"
hmac = "0.12"
pbkdf2 = "0.12"
base64 = "0.22"
log = "0.4"
regex = "1"
unicode-normalization = "0.1"
md-5 = "0.10"
s2 = "0.0.13"

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
