#ifndef SMONGO_H
#define SMONGO_H

/* Auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define SMONGO_OK 0

#define SMONGO_ERROR -1

#define SMONGO_ERROR_NULL_PTR -2

#define SMONGO_ERROR_INVALID_UTF8 -3

#define SMONGO_ERROR_INVALID_BSON -4

#define SMONGO_ERROR_NOT_FOUND -5

/**
 * Opaque collection handle — C consumers only see a pointer.
 */
typedef struct SmongoCollection SmongoCollection;

/**
 * Opaque cursor for iterating query results — C consumers only see a pointer.
 */
typedef struct SmongoCursor SmongoCursor;

/**
 * Opaque database handle — C consumers only see a pointer.
 */
typedef struct SmongoDb SmongoDb;

/**
 * Opaque session handle for multi-collection transactions.
 */
typedef struct SmongoSession SmongoSession;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Open or create a database at the given filesystem path.
 *
 * On success, writes a heap-allocated `SmongoDb` handle into `*out` and
 * returns `SMONGO_OK`.  The caller must eventually pass this handle to
 * `smongo_close`.
 *
 * # Safety
 * * `path` must be a valid, NUL-terminated C string.
 * * `out` must be a valid pointer to a `*mut SmongoDb`.
 */
int32_t smongo_open(const char *path, struct SmongoDb **out);

/**
 * Close the database and free the handle.
 *
 * After this call, `db` is invalid and must not be used.
 *
 * # Safety
 * `db` must be a handle previously returned by `smongo_open`, or null
 * (in which case this is a no-op).
 */
void smongo_close(struct SmongoDb *db);

/**
 * Drop the entire database, removing all data files.
 *
 * This consumes the database handle — it must not be used after this call.
 * Pass null for a no-op.
 *
 * # Safety
 * `db` must be a handle previously returned by `smongo_open`, or null.
 */
int32_t smongo_drop(struct SmongoDb *db);

/**
 * List all collection names in the database.
 *
 * On success, writes a BSON document containing a `names` array of strings
 * into `*result` / `*result_len`. Free the result with `smongo_free`.
 *
 * # Safety
 * `db`, `result`, and `result_len` must be valid pointers.
 */
int32_t smongo_list_collection_names(struct SmongoDb *db, uint8_t **result, uintptr_t *result_len);

/**
 * Drop a collection by name.
 *
 * # Safety
 * `db` must be a valid `SmongoDb` handle. `name` must be a valid C string.
 */
int32_t smongo_drop_collection(struct SmongoDb *db, const char *name);

/**
 * Get database statistics.
 *
 * On success, writes a BSON document containing `collectionCount` and
 * `sizeBytes` into `*result` / `*result_len`.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_stats(struct SmongoDb *db, uint8_t **result, uintptr_t *result_len);

/**
 * Obtain a collection handle from an open database.
 *
 * On success, writes a heap-allocated `SmongoCollection` into `*out`.
 * The caller must free it with `smongo_collection_free`.
 *
 * # Safety
 * * `db` must be a valid `SmongoDb` handle.
 * * `name` must be a valid, NUL-terminated C string.
 * * `out` must be a valid pointer to a `*mut SmongoCollection`.
 */
int32_t smongo_collection(struct SmongoDb *db, const char *name, struct SmongoCollection **out);

/**
 * Free a collection handle.
 *
 * # Safety
 * `col` must be a handle previously returned by `smongo_collection`, or null.
 */
void smongo_collection_free(struct SmongoCollection *col);

/**
 * Insert a single BSON document into the collection.
 *
 * On success, writes the result (a BSON document containing `insertedId`)
 * into `*result` / `*result_len`.  Free the result buffer with `smongo_free`.
 *
 * # Safety
 * All pointer arguments must be valid. `doc` must point to `doc_len` bytes
 * of valid BSON.
 */
int32_t smongo_insert_one(struct SmongoCollection *col,
                          const uint8_t *doc,
                          uintptr_t doc_len,
                          uint8_t **result,
                          uintptr_t *result_len);

/**
 * Insert multiple BSON documents into the collection.
 *
 * `docs` must be a BSON document whose keys are stringified array indices
 * ("0", "1", ...), each mapping to a document — the standard BSON
 * array-as-document representation.
 *
 * On success, writes a BSON result document containing `insertedIds` (an
 * array of the generated IDs) into `*result` / `*result_len`.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_insert_many(struct SmongoCollection *col,
                           const uint8_t *docs,
                           uintptr_t docs_len,
                           uint8_t **result,
                           uintptr_t *result_len);

/**
 * Find all documents matching the BSON filter, returning a cursor.
 *
 * On success, writes a cursor handle into `*cursor_out`.  Iterate with
 * `smongo_cursor_next` and free with `smongo_cursor_free`.
 *
 * # Safety
 * All pointer arguments must be valid. `filter` must point to valid BSON.
 */
int32_t smongo_find(struct SmongoCollection *col,
                    const uint8_t *filter,
                    uintptr_t filter_len,
                    struct SmongoCursor **cursor_out);

/**
 * Find a single document matching the BSON filter.
 *
 * On success, writes the matching document's BSON bytes into
 * `*result` / `*result_len`.  Returns `SMONGO_ERROR_NOT_FOUND` if no
 * document matches (with `*result` set to null).
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_find_one(struct SmongoCollection *col,
                        const uint8_t *filter,
                        uintptr_t filter_len,
                        uint8_t **result,
                        uintptr_t *result_len);

/**
 * Find all documents with options (sort/limit/skip/projection).
 *
 * `options` is a BSON document with optional keys: `sort`, `limit`, `skip`, `projection`.
 * Pass null/0 for options/options_len to use defaults (equivalent to `smongo_find`).
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_find_with_options(struct SmongoCollection *col,
                                 const uint8_t *filter,
                                 uintptr_t filter_len,
                                 const uint8_t *options,
                                 uintptr_t options_len,
                                 struct SmongoCursor **cursor_out);

/**
 * Find one document with options (sort/projection).
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_find_one_with_options(struct SmongoCollection *col,
                                     const uint8_t *filter,
                                     uintptr_t filter_len,
                                     const uint8_t *options,
                                     uintptr_t options_len,
                                     uint8_t **result,
                                     uintptr_t *result_len);

/**
 * Update a single document matching the filter.
 *
 * On success, writes a BSON result document containing `matchedCount` and
 * `modifiedCount` into `*result` / `*result_len`.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_update_one(struct SmongoCollection *col,
                          const uint8_t *filter,
                          uintptr_t filter_len,
                          const uint8_t *update,
                          uintptr_t update_len,
                          uint8_t **result,
                          uintptr_t *result_len);

/**
 * Update a single document with options (e.g. upsert).
 *
 * `options` is a BSON document with optional keys: `upsert` (bool).
 * Pass null/0 for options/options_len to use defaults.
 *
 * Result includes `matchedCount`, `modifiedCount`, and optionally `upsertedId`.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_update_one_with_options(struct SmongoCollection *col,
                                       const uint8_t *filter,
                                       uintptr_t filter_len,
                                       const uint8_t *update,
                                       uintptr_t update_len,
                                       const uint8_t *options,
                                       uintptr_t options_len,
                                       uint8_t **result,
                                       uintptr_t *result_len);

/**
 * Delete a single document matching the filter.
 *
 * On success, writes a BSON result document containing `deletedCount`
 * into `*result` / `*result_len`.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_delete_one(struct SmongoCollection *col,
                          const uint8_t *filter,
                          uintptr_t filter_len,
                          uint8_t **result,
                          uintptr_t *result_len);

/**
 * Update all documents matching the filter.
 *
 * On success, writes a BSON result document containing `matchedCount` and
 * `modifiedCount` into `*result` / `*result_len`.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_update_many(struct SmongoCollection *col,
                           const uint8_t *filter,
                           uintptr_t filter_len,
                           const uint8_t *update,
                           uintptr_t update_len,
                           uint8_t **result,
                           uintptr_t *result_len);

/**
 * Delete all documents matching the filter.
 *
 * On success, writes a BSON result document containing `deletedCount`
 * into `*result` / `*result_len`.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_delete_many(struct SmongoCollection *col,
                           const uint8_t *filter,
                           uintptr_t filter_len,
                           uint8_t **result,
                           uintptr_t *result_len);

/**
 * Count documents matching the BSON filter.
 *
 * Pass null for `filter` / 0 for `filter_len` to count all documents.
 *
 * # Safety
 * `col` and `count_out` must be valid pointers.
 */
int32_t smongo_count(struct SmongoCollection *col,
                     const uint8_t *filter,
                     uintptr_t filter_len,
                     int64_t *count_out);

/**
 * Advance the cursor and get the next document's BSON bytes.
 *
 * Returns `SMONGO_OK` while documents remain.  When the cursor is
 * exhausted, returns `SMONGO_ERROR_NOT_FOUND` with `*doc` set to null.
 *
 * The returned pointer is valid until the next call to `smongo_cursor_next`
 * or `smongo_cursor_free` on the same cursor.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_cursor_next(struct SmongoCursor *cursor, const uint8_t **doc, uintptr_t *doc_len);

/**
 * Free a cursor and all its resources.
 *
 * # Safety
 * `cursor` must be a handle previously returned by `smongo_find` or
 * `smongo_aggregate`, or null (no-op).
 */
void smongo_cursor_free(struct SmongoCursor *cursor);

/**
 * Create an index on the collection.
 *
 * `keys` is a BSON document mapping field names to direction (1 or -1).
 * `name` may be null to auto-generate the index name.
 *
 * On success, writes a BSON result document containing `indexName` into
 * `*result` / `*result_len`.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_create_index(struct SmongoCollection *col,
                            const uint8_t *keys,
                            uintptr_t keys_len,
                            const char *name,
                            int32_t unique,
                            uint8_t **result,
                            uintptr_t *result_len);

/**
 * Drop an index by name.
 *
 * # Safety
 * `col` must be a valid collection handle. `name` must be a valid C string.
 */
int32_t smongo_drop_index(struct SmongoCollection *col, const char *name);

/**
 * List all indexes on the collection.
 *
 * On success, writes a BSON document containing an `indexes` array into
 * `*result` / `*result_len`. Each element is a document with `name`, `keys`,
 * and `options` fields.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_list_indexes(struct SmongoCollection *col, uint8_t **result, uintptr_t *result_len);

/**
 * Rebuild all indexes on the collection.
 *
 * On success, writes the number of index entries rebuilt into `*count_out`.
 *
 * # Safety
 * `col` and `count_out` must be valid pointers.
 */
int32_t smongo_rebuild_all_indexes(struct SmongoCollection *col, int64_t *count_out);

/**
 * Explain the execution plan for a find query.
 *
 * On success, writes a BSON explain document into `*result` / `*result_len`.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_explain_find(struct SmongoCollection *col,
                            const uint8_t *filter,
                            uintptr_t filter_len,
                            uint8_t **result,
                            uintptr_t *result_len);

/**
 * Explain the execution plan for a find-one query.
 *
 * On success, writes a BSON explain document into `*result` / `*result_len`.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_explain_find_one(struct SmongoCollection *col,
                                const uint8_t *filter,
                                uintptr_t filter_len,
                                uint8_t **result,
                                uintptr_t *result_len);

/**
 * Execute an aggregation pipeline.
 *
 * The pipeline is passed as a BSON document whose top-level keys are the
 * stringified array indices ("0", "1", "2", ...), each mapping to a stage
 * document.  This is the standard BSON array-as-document representation.
 *
 * On success, writes a cursor handle into `*cursor_out`.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_aggregate(struct SmongoCollection *col,
                         const uint8_t *pipeline,
                         uintptr_t pipeline_len,
                         struct SmongoCursor **cursor_out);

/**
 * Explain how an aggregation pipeline's initial data fetch would execute.
 *
 * Runs the pipeline optimizer, extracts leading `$match` stages, and returns
 * a BSON document with the execution plan, index used, and statistics.
 *
 * On success, writes the explain BSON into `*result` / `*result_len`.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_explain_aggregate(struct SmongoCollection *col,
                                 const uint8_t *pipeline,
                                 uintptr_t pipeline_len,
                                 uint8_t **result,
                                 uintptr_t *result_len);

/**
 * Start a new session for multi-collection transactions.
 *
 * On success, writes a heap-allocated `SmongoSession` handle into `*out`.
 * Free with `smongo_session_free`.
 *
 * # Safety
 * `db` must be a valid `SmongoDb` handle. `out` must be a valid pointer.
 */
int32_t smongo_start_session(struct SmongoDb *db, struct SmongoSession **out);

/**
 * Begin a transaction on the session.
 *
 * # Safety
 * `session` must be a valid `SmongoSession` handle.
 */
int32_t smongo_session_begin_transaction(struct SmongoSession *session);

/**
 * Commit the current transaction on the session.
 *
 * # Safety
 * `session` must be a valid `SmongoSession` handle.
 */
int32_t smongo_session_commit_transaction(struct SmongoSession *session);

/**
 * Rollback the current transaction on the session.
 *
 * # Safety
 * `session` must be a valid `SmongoSession` handle.
 */
int32_t smongo_session_rollback_transaction(struct SmongoSession *session);

/**
 * Insert a document into a collection within this session's transaction.
 *
 * On success, writes the BSON result (`insertedId`) into `*result` / `*result_len`.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_session_insert_one(struct SmongoSession *session,
                                  const char *coll_name,
                                  const uint8_t *doc,
                                  uintptr_t doc_len,
                                  uint8_t **result,
                                  uintptr_t *result_len);

/**
 * Find all documents in a collection within this session's transaction.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_session_find(struct SmongoSession *session,
                            const char *coll_name,
                            const uint8_t *filter,
                            uintptr_t filter_len,
                            struct SmongoCursor **cursor_out);

/**
 * Find one document in a collection within this session's transaction.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_session_find_one(struct SmongoSession *session,
                                const char *coll_name,
                                const uint8_t *filter,
                                uintptr_t filter_len,
                                uint8_t **result,
                                uintptr_t *result_len);

/**
 * Delete a single document in a collection within this session's transaction.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_session_delete_one(struct SmongoSession *session,
                                  const char *coll_name,
                                  const uint8_t *filter,
                                  uintptr_t filter_len,
                                  uint8_t **result,
                                  uintptr_t *result_len);

/**
 * Update a single document in a collection within this session's transaction.
 *
 * On success, writes a BSON result document containing `matchedCount` and
 * `modifiedCount` into `*result` / `*result_len`.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_session_update_one(struct SmongoSession *session,
                                  const char *coll_name,
                                  const uint8_t *filter,
                                  uintptr_t filter_len,
                                  const uint8_t *update,
                                  uintptr_t update_len,
                                  uint8_t **result,
                                  uintptr_t *result_len);

/**
 * Update all documents matching the filter within this session's transaction.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_session_update_many(struct SmongoSession *session,
                                   const char *coll_name,
                                   const uint8_t *filter,
                                   uintptr_t filter_len,
                                   const uint8_t *update,
                                   uintptr_t update_len,
                                   uint8_t **result,
                                   uintptr_t *result_len);

/**
 * Delete all documents matching the filter within this session's transaction.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_session_delete_many(struct SmongoSession *session,
                                   const char *coll_name,
                                   const uint8_t *filter,
                                   uintptr_t filter_len,
                                   uint8_t **result,
                                   uintptr_t *result_len);

/**
 * Run an aggregation pipeline within this session's transaction.
 *
 * Pipeline format is the same as `smongo_aggregate` — a BSON document with
 * keys "0", "1", ... mapping to stage documents.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_session_aggregate(struct SmongoSession *session,
                                 const char *coll_name,
                                 const uint8_t *pipeline,
                                 uintptr_t pipeline_len,
                                 struct SmongoCursor **cursor_out);

/**
 * Count documents in a collection within this session's transaction.
 *
 * Pass null for `filter` / 0 for `filter_len` to count all documents.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_session_count(struct SmongoSession *session,
                             const char *coll_name,
                             const uint8_t *filter,
                             uintptr_t filter_len,
                             int64_t *count_out);

/**
 * Free a session handle.
 *
 * # Safety
 * `session` must be a handle previously returned by `smongo_start_session`,
 * or null (no-op).
 */
void smongo_session_free(struct SmongoSession *session);

/**
 * Reap expired documents from all TTL-indexed collections in the database.
 *
 * On success, writes the number of removed documents into `*count_out`.
 *
 * # Safety
 * `db` and `count_out` must be valid pointers.
 */
int32_t smongo_reap_ttl(struct SmongoDb *db, int64_t *count_out);

/**
 * Create an index with TTL (expire_after_seconds) support.
 *
 * Pass `expire_after_seconds < 0` to create a non-TTL index.
 *
 * On success, writes a BSON result document containing `indexName` into
 * `*result` / `*result_len`.
 *
 * # Safety
 * All pointer arguments must be valid.
 */
int32_t smongo_create_index_with_ttl(struct SmongoCollection *col,
                                     const uint8_t *keys,
                                     uintptr_t keys_len,
                                     int32_t unique,
                                     int64_t expire_after_seconds,
                                     uint8_t **result,
                                     uintptr_t *result_len);

/**
 * Get the last error message for the current thread.
 *
 * Returns a NUL-terminated string pointer that is valid until the next
 * smongo API call on the same thread.  Returns null if no error.
 *
 * # Safety
 * This function is always safe to call.
 */
const char *smongo_last_error(void);

/**
 * Free a buffer previously returned by a smongo function.
 *
 * # Safety
 * * `ptr` must have been returned by a smongo function (e.g.
 *   `smongo_insert_one`, `smongo_find_one`, etc.), or be null (no-op).
 * * `len` must match the `*result_len` value that was written alongside
 *   the pointer.
 * * The buffer must not have been freed already.
 */
void smongo_free(uint8_t *ptr, uintptr_t len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SMONGO_H */
